import React from "react";
import {
  View,
  Text,
  ImageBackground,
  StyleSheet,
  Image,
  ScrollView,
} from "react-native";
import { Paragraph, Headline, Subheading } from "react-native-paper";

function MissionScreen() {
  return (
    <View style={{ flex: 1, alignItems: "center", backgroundColor: "white" }}>
      <ScrollView style={{ padding: 5 }}>
        <Text style={styles.sectionText}>VISION AND MISSION</Text>
        <View style={styles.mainCardView}>
          <Text style={styles.title}>Vision</Text>
          <Text style={styles.text}>
            A leading global Technopolis and innovation hub.
          </Text>

          <Text style={styles.title}>Mission</Text>
          <Text style={styles.text}>
            To develop a thriving sustainable smart city and a vibrant
            innovation ecosystem contributing to Kenya's knowledge Economy.
          </Text>

          <Text style={styles.paragraph}>
            The Government of Kenya established the Konza Technopolis
            Development Authority (KoTDA) as a special purpose entity to
            facilitate the development of Konza. The mission of KoTDA is to
            ensure that Konza grows into a sustainable, world-class technology
            hub and a major economic driver for the nation, with a vibrant mix
            of businesses, workers, residents, and urban amenities. KoTDA is
            responsible for overseeing the development and management of Konza,
            and for establishing a strong value proposition for businesses to
            locate and expand in Konza. KoTDA’s Board of Directors was appointed
            in 2013. The Board is currently overseeing the development of
            infrastructure for Phase 1 of Konza.
          </Text>
        </View>
        <Text style={styles.sectionText}>OUR MANDATE</Text>
        <View style={styles.mainCardView}>
          <Text style={styles.subtitle}>Market and Promote</Text>
          <Text style={styles.text}>
            Establish a strong value proposition to encourage businesses to move
            to Konza. Attract real estate developers and prospective tenants.
          </Text>

          <Text style={styles.subtitle}>Finance public infrastructure</Text>
          <Text style={styles.text}>
            Secure funding from the Central Government to provide incentives,
            services, and infrastructure to move Konza forward. Redirect, in a
            flexible and independent manner, the national government funding
            secured. Collect user fees, assessments, and other revenues, and
            re-invest the funds generated back into Konza. Borrow capital funds
            at attractive market rates, in order to effectively leverage
            resources, with the resultant debt being serviced by either revenues
            generated by the project, national government guarantees, or both..
          </Text>

          <Text style={styles.subtitle}>Manage distribution of parcels</Text>
          <Text style={styles.text}>
            Lease Konza land through a 99-year ground lease from the federal
            government. Negotiate sub-leases with developers for parcel
            development.
          </Text>

          <Text style={styles.subtitle}>Develop public infrastructure</Text>
          <Text style={styles.text}>
            Oversee real estate development and fund physical infrastructure,
            either independently or through public private partnerships (PPPs).
          </Text>

          <Text style={styles.subtitle}>Regulate development</Text>
          <Text style={styles.text}>
            Guide real estate development according to master plan principles.
            Create and administer incentives to businesses.
          </Text>

          <Text style={styles.subtitle}>Manage transaction services</Text>
          <Text style={styles.text}>
            Facilitate business at Konza through expeditious and clear one-stop
            procurement and permitting. Provide and oversee PPP provision of
            high-quality services. Collaborate with appropriate governmental
            entities to obtain high-quality municipal services.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-between",
    backgroundColor: "white",
    padding: 10,
  },
  sectionText: {
    flex: 0,
    textAlign: "center",
    color: "white",
    padding: 5,
    fontSize: 18,
    fontWeight: "bold",
    backgroundColor: "green",
    marginVertical: 10,
  },
  image: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    alignSelf: "flex-start",
    fontSize: 14,
  },
  paragraph: {
    fontSize: 14,
    alignSelf: "center",
    paddingVertical: 20,
  },
  title: {
    fontWeight: "bold",
    fontSize: 18,
    alignSelf: "center",
    paddingVertical: 15,
  },
  subtitle: {
    fontWeight: "bold",
    fontSize: 17,
    alignSelf: "center",
    paddingVertical: 10,
  },
  mainCardView: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 5,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    padding: 10,
    paddingLeft: 14,
    paddingRight: 14,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 0,
    marginRight: 0,
  },
});

export default MissionScreen;
